### ISSUE TITLE
Craft 5 Upgrade

### ISSUE THREAD

**Issue by wbrowar** [mwikala/linode-s3#7]
Hi, @mwikala, will you be releasing this plugin for Craft 5? Here's the upgrade guide that I've found helpful in my own plugins: https://craftcms.com/docs/5.x/extend/updating-plugins.html

For me there were some class changes, but for the most part PHPStan caught most of the things that needed updating.

Thanks for putting this plugin together! I've been using it since you first released it and it's made working with Linode’s object storage super easy to deal with.

**Comment by mwikala** [comment]
Thanks for putting this on my radar, I welcome any pull requests doing the upgrade. I might not be able to get round to this for a few weeks

**Comment by wbrowar** [comment]
No worries! I haven't worked on an asset plugin before, but I can take a look and see how far I get with the upgrade.

**Comment by wbrowar** [comment]
Hi @mwikala, I gave this a go, but I'm not exactly sure what I'm doing. I think it'll be safer to let you take this update 😬

**Comment by ttempleton** [comment]
I just gave this a look (admittedly using the plugin with Wasabi rather than Linode). Rector ran without making any changes, and I just changed the composer.json requirements to `"craftcms/cms": "^4.0.0-beta.4|^5.0.0"` and `"craftcms/flysystem": "^1.0.0-beta.2|^2.0.0"`, and so far it's working fine.

**Comment by wbrowar** [comment]
@mwikala, do you think this is good enough to merge in @ttempleton’s PR and tag a release to publish this version?
